version: "2"
run:
  issues-exit-code: 1
  tests: false
  build-tags:
    - nobadger
    - nomysql
    - nopgx
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errname
    - exhaustive
    - gosec
    - govet
    - importas
    - ineffassign
    - misspell
    - prealloc
    - promlinter
    - sloglint
    - sqlclosecheck
    - staticcheck
    - testableexamples
    - testifylint
    - tparallel
    - unconvert
    - unused
    - wastedassign
    - whitespace
    - zerologlint
  settings:
    staticcheck:
      checks: ["all", "-SA6002", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022",  "-QF1006", "-QF1008"]
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: modules/l4rdp/matcher.go
        text: G101 # There are no hardcoded credentials.
      - linters:
          - gosec
        path: modules/l4proxy/loadbalancing.go
        text: G404 # The choice of weakrand is deliberate.
      - linters:
          - gosec
        path: modules/l4openvpn/crypto.go
        text: G501 # crypto/md5 is supported for compatibility purposes.
      - linters:
          - gosec
        path: modules/l4openvpn/crypto.go
        text: G505 # crypto/sha1 is supported for compatibility purposes.
    paths: []
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard # Standard section: captures all standard packages.
        - default # Default section: contains all imports that could not be matched to another section type.
        - prefix(github.com/mholt/caddy-l4) # Custom section: groups all imports with the specified Prefix.
      custom-order: true
  exclusions:
    generated: lax
    paths: []
